<a href="https://colab.research.google.com/github/rr-y/DL_Lab/blob/master/DL107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [7]:
%%time
t = torch.zeros([3,3])
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
CPU times: user 2.21 ms, sys: 2.81 ms, total: 5.02 ms
Wall time: 156 ms


In [10]:
%%time
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
CPU times: user 340 µs, sys: 896 µs, total: 1.24 ms
Wall time: 6.82 ms


In [11]:
%%time 
t = torch.ones([3,4], requires_grad=True)
print(t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
CPU times: user 4.02 ms, sys: 0 ns, total: 4.02 ms
Wall time: 50.9 ms


In [12]:
%%time = torch.zeros_like([3,4], equires_grad=True)
print(t)

UsageError: Can't use statement directly after '%%time'!


In [14]:
%%time
t = torch.linspace(1,5,100)
print(t)

tensor([1.0000, 1.0404, 1.0808, 1.1212, 1.1616, 1.2020, 1.2424, 1.2828, 1.3232,
        1.3636, 1.4040, 1.4444, 1.4848, 1.5253, 1.5657, 1.6061, 1.6465, 1.6869,
        1.7273, 1.7677, 1.8081, 1.8485, 1.8889, 1.9293, 1.9697, 2.0101, 2.0505,
        2.0909, 2.1313, 2.1717, 2.2121, 2.2525, 2.2929, 2.3333, 2.3737, 2.4141,
        2.4545, 2.4949, 2.5354, 2.5758, 2.6162, 2.6566, 2.6970, 2.7374, 2.7778,
        2.8182, 2.8586, 2.8990, 2.9394, 2.9798, 3.0202, 3.0606, 3.1010, 3.1414,
        3.1818, 3.2222, 3.2626, 3.3030, 3.3434, 3.3838, 3.4242, 3.4646, 3.5051,
        3.5455, 3.5859, 3.6263, 3.6667, 3.7071, 3.7475, 3.7879, 3.8283, 3.8687,
        3.9091, 3.9495, 3.9899, 4.0303, 4.0707, 4.1111, 4.1515, 4.1919, 4.2323,
        4.2727, 4.3131, 4.3535, 4.3939, 4.4343, 4.4747, 4.5152, 4.5556, 4.5960,
        4.6364, 4.6768, 4.7172, 4.7576, 4.7980, 4.8384, 4.8788, 4.9192, 4.9596,
        5.0000])
CPU times: user 3.67 ms, sys: 81 µs, total: 3.75 ms
Wall time: 6.06 ms


In [15]:
%%time
t = torch.empty([3,4])

CPU times: user 447 µs, sys: 0 ns, total: 447 µs
Wall time: 8.42 ms


In [21]:
# size calculation of tensors
t = t.view(4,3)
print(t.shape)

torch.Size([4, 3])


In [31]:
## lets try out some examples
# here are some examples of autograd function
x = torch.ones([3,3], requires_grad = True)
y = 3*x+2
z = y.mean()
z.backward()
print(x.grad)

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


In [36]:
# differenciate y = 3*x*x+6*x+9

x = torch.tensor([3], requires_grad=True, dtype=float)
y = 3*x*x + 8*x+ 9
print("Y : ",y)
z = y.sum()
print("Z : ",z)
z.backward()
print(x.grad)

Y :  tensor([60.], dtype=torch.float64, grad_fn=<AddBackward0>)
Z :  tensor(60., dtype=torch.float64, grad_fn=<SumBackward0>)
tensor([26.], dtype=torch.float64)


In [56]:
## lets predict the value
## original equation--> y = 3*x+2
w = torch.ones([1], requires_grad=True)
b = torch.ones([1], requires_grad=True)
for _ in range(50):
  x = torch.randn([1], requires_grad = True)
  y = 8*x+9
  y_hat = w*x+b
  loss = ((y_hat-y)**2).sum()
  loss.backward()
  with torch.no_grad():
    w -= 0.1*w.grad
    b -= 0.1*b.grad
    w.grad.zero_()
    b.grad.zero_()

print(w.item(),b.item())

7.999116897583008 8.999595642089844


In [63]:
## lets have a look of argmax
t = torch.randn([3,4])
print(t)
print(t.argmax(dim=1))
print(t.sum(dim=-1).unsqueeze(1))


tensor([[-1.1075, -0.3489, -0.5154,  0.0569],
        [-0.3059, -0.1655, -0.3471,  0.3812],
        [ 0.4464,  1.4413,  0.6538, -0.3663]])
tensor([3, 3, 1])
tensor([[-1.9148],
        [-0.4373],
        [ 2.1751]])
